baseURL: https://paperless-forest.ru
languageCode: ru-ru
DefaultContentLanguage: ru
timezone: Asia/Baku

# Book configuration
disablePathToLower: true
enableGitInfo: true

# # Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1





# Tags
taxonomies:
  tag: tags


  
# Sidebar menu additional links
menu:
  before:
    - name: "Лента"
      url: "/blog"
      weight: 1
#  after:
#    - name: "Github"
#      url: "https://github.com/anareaty/anareaty.github.io"
#      weight: 10
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/anareaty/
      params:
          icon: github-fill
    - identifier: telegram
      name: Telegram
      url: https://t.me/anareaty
      params:
          icon: telegram-line
    - identifier: mastodon
      name: Mastodon
      url: https://mastodon.social/@reaty
      params:
          icon: mastodon-fill


params:

  name: Anareaty
  title: Paperless Forest

  # OPTIONAL: custom favicon location
  # favicon: 'location/to/favicon.png'

  # Enable rendering of LaTeX blocks
  # (surrounded by either single or double dollar signs)
  enableLatex: true

  # whether to render titles for code blocks
  enableCodeBlockTitle: true

  # whether to render copy buttons for code blocks
  enableCodeBlockCopy: true

  # whether to render callouts
  enableCallouts: true

  # whether to render mermaid diagrams
  enableMermaid: true

  # Link to your Github repo
  GitHubLink: https://github.com/anareaty/anareaty.github.io

  # Search (WIP)
  search:
    enableSemanticSearch: false
    operandApiKey: "REPLACE-WITH-YOUR-OPERAND-API-KEY"
    operandIndexId: "REPLACE-WITH-YOUR-OPERAND-INDEX-ID"

  # Site description and title
  description:
    Где растут идеи

  
  # Footer links
  # links:
  #  - link_name: Website
  #    link: https://bencuan.me
  #  - link_name: Blog
  #    link: https://blog.bencuan.me

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  toc: true

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: "January 2, 2006"


  # (Optional, default true) Enables comments template on pages
  # By default partals/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  #BookComments: true



  # Don't change this
  #enableSPA: false
  #BookSearch: false
  #BookServiceWorker: false
  #BookPortableLinks: false
